### ISSUE TITLE
Dashboard crashes after a few hours

### ISSUE THREAD

**Issue by holgersindbaek** [gottfrois/dashing-rails#83]
Seems like my Dashing dashboard crashes after a few hours of being live. Then I need to restart the server and everything is fine again. This is the crash log from the server:

https://gist.github.com/holgersindbaek/c81c6c5ba9221519bd97

I'm not sure what could be wrong here. Any guesses?!

**Comment by gottfrois** [comment]
Looks like a Timeout Error occured. What are you doing in the job?

**Comment by holgersindbaek** [comment]
@gottfrois It seems to be failing on line 43, where it's trying to send an event - https://gist.github.com/holgersindbaek/5661a6750002b2c39c9a - so I'm guessing it might have something to do with the lost connection - https://github.com/gottfrois/dashing-rails/issues/82#issuecomment-174899758. What do you think?

Do I need to upgrade to the hobby dyno on Heroku for this to work?

**Comment by gottfrois** [comment]
If you dynos go into sleep mode, it might be the reason yes.

**Comment by holgersindbaek** [comment]
Hmmm ok. I've upgrade to the hobby dyno, added the domain to Pingdom.com, so it will be hit every 15 min and set an event to be sent from the jobs every 40 seconds. It's been up for around 2 hours now and seems fine.

I'll close by the end of the day, if it's still fine then.

Can you explain me what the minimum/maximum puma threads do in relation to dashing-rails? I'm talking about this code "puma -t 0:5". Could the issue I was experiencing have something to do with the dashboard being show on several browsers?

**Comment by holgersindbaek** [comment]
Seems like things are working now, after I made those changes. Thanks for the feedback. Gonna close the issue.

**Comment by gottfrois** [comment]
Basically you need a long-live connection opened on your server used by the `EventsController`. If you have 5 dashboards opened, your server need to handle at least 5 concurrent requests. This is why we use puma web server in order to handle concurrent requests using threads.

Dashing-Rails uses Rails `ActionController::Live` to push events to a given dashboard page. I believe this kind of hard limitation could be solved using Rails `ActionCable` in the futur.
